name: ğŒ™ğŒ€ğŒ™ğŒ‰ğŒ“ğŒğŒ ğŒˆğŒğŒ‚ğŒ”ğŒ„ğŒ
# name: ğŒ™ğŒ€ğŒ‚ğŒ”ğŒ‰ğŒ“ğŒ–ğŒ€ğŒ• ğŒˆğŒğŒ‚ğŒ”ğŒ„ğŒ
url: "https://shanekrusen.github.io/bescoth-norichach/"
collections:
    articles:
      output: true

#build
host: 0.0.0.0
sass:
    sass_dir: _sass