name: ğŒ™ğŒ€ğŒ™ğŒ‰ğŒ“ğŒğŒ ğŒˆğŒğŒ‚ğŒ”ğŒ„ğŒ
repository: https://github.com/shanekrusen/bescoth-norichach
url: "https://shanekrusen.github.io/bescoth-norichach/"

#build
host: 0.0.0.0
sass:
    sass_dir: _sass